name: 'Call reusable workflow CodeQL Scan python'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  call-workflow-scan-python:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: Cloud-NC-Engineering-Thailand/template-codeql/reuseable-scan-code.yaml@master
    with:
      language: 'python'
      path: 'python-code-folder'
  
