name: 'Call reusable workflow CodeQL iac Scan'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  call-workflow-scan-terraform:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: Cloud-NC-Engineering-Thailand/template-codeql/.github/workflows/reuseable-scan-iac-code.yaml@master
    with:
      path: terraform-code-folder