name: 'Call reusable workflow CodeQL Scan dotnet'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  call-workflow-scan-dotnet:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: Cloud-NC-Engineering-Thailand/template-codeql/reuseable-scan-code.yaml@master
    with:
      language: 'csharp'
      path: 'dotnet-code-folder'
