name: 'CodeQL Scan'
on:
  workflow_call:
    inputs:
      language:
        description: 'Programming language for CodeQL analysis'
        required: true
        type: string
      path:
        description: 'Path of code to be scanned'
        required: true
        type: string

jobs:
  call-workflow-scan-python:
    uses: uoio1/reusable-workflow/.github/workflows/reuseable-scan-code.yaml@master
    with:
      language: python
      path: python-code-folder
