name: 'Call reusable workflow CodeQL Scan'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  call-workflow-scan-python:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: uoio1/reusable-workflow/.github/workflows/reuseable-scan-code.yaml@master
    with:
      language: 'Python'
      path: 'python-code-folder'
